dataset_name: epic
train_split: ['training']
val_split: ['validation']
init_rand_seed: 1004
dataset: {
  json_file: /data/epic_kitchens_slowfast/annotations/epic_kitchens_100_noun.json,
  feat_folder: /data/epic_kitchens_slowfast/features,
  file_prefix: ~,
  file_ext: .npz,
  num_classes: 300,
  input_dim: 2304,
  feat_stride: 16,
  num_frames: 32,
  default_fps: 30,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 10000]],
  fpn_type: fusion, # identity, fpn, fusion
  max_buffer_len_factor: 4.0,
  n_mha_win_size: -1, 
}
opt: {
  learning_rate: 0.0001,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 4,
}
train_cfg: {
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.25,  
  droppath: 0.1, 
  label_smoothing: 0.1,
}
test_cfg: {
  pre_nms_topk: 5000,
  max_seg_num: 3000,  
  min_score: 0.001,
  nms_sigma : 0.35,  
  multiclass_nms: True
}
output_folder: ./ckpt/